[workspace]
members = [
    "stream",
    "ipfs",
    "indexer_utils",

    "search-indexer",
    "search-indexer-shared",
    "search-indexer-repository",
    "search-admin",

    "sdk",

    "hermes-kafka",
    "hermes-schema",
    "hermes-relay",
    "hermes-pipeline",
    "hermes-ipfs-cache",
    "hermes-instrumentation",

    "atlas",
    "hermes-substream",

    "kg-indexer",
    "scoring-service/vote-indexer",
    "scoring-service/topology-indexer",
]
# `substreams build` doesn't work well when in a workspace. The CLI looks for the
# target directory within the substream crate, but the workspace hoists it to the
# workspace root. indexer-substream still uses prost 0.11, so it remains excluded.
exclude = ["indexer-substream"]
resolver = "2"
