[workspace]
members = [
    "stream",
    "ipfs",
    "indexer_utils",

    "search-indexer",
    "search-indexer-shared",
    "search-indexer-repository",
    "search-admin",

    "sdk",

    "hermes-kafka",
    "hermes-schema",
    "hermes-relay",
    "hermes-pipeline",
    "hermes-ipfs-cache",
    "hermes-instrumentation",

    "chain-tip-exporter",

    "atlas",
    "hermes-substream",

    "kg-indexer",
    "scoring-service/vote-indexer",
    "scoring-service/topology-indexer",

    "notification-service/notification-indexer",
    "notification-service/delivery-worker",
    "notification-service/e2e-tests",
]
resolver = "2"
