// This file is @generated by prost-build.
/// HermesBlockSummary - canonical per-block summary emitted by hermes-pipeline.
///
/// This message is emitted to a dedicated topic for downstream consumers to
/// reconcile event completeness and close batches deterministically.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesBlockSummary {
    #[prost(uint64, tag = "1")]
    pub block_number: u64,
    #[prost(string, tag = "2")]
    pub cursor: ::prost::alloc::string::String,
    /// Unix timestamp in seconds
    #[prost(uint64, tag = "3")]
    pub created_at: u64,
    #[prost(uint64, tag = "4")]
    pub total_events: u64,
    /// Counts keyed by Kafka topic name.
    #[prost(map = "string, uint64", tag = "5")]
    pub counts_by_topic: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u64,
    >,
    /// Counts keyed by event type (e.g., ROLE_GRANTED, PROPOSAL_CREATED).
    #[prost(map = "string, uint64", tag = "6")]
    pub counts_by_event_type: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u64,
    >,
}
