// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockchainMetadata {
    /// Unix timestamp in seconds
    #[prost(uint64, tag = "1")]
    pub created_at: u64,
    /// address
    #[prost(bytes = "vec", tag = "2")]
    pub created_by: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub block_number: u64,
    #[prost(string, tag = "4")]
    pub cursor: ::prost::alloc::string::String,
}
