// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserEvent {
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "EventType", tag = "4")]
    pub event_type: i32,
    #[prost(message, optional, tag = "5")]
    pub data: ::core::option::Option<UserEventData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserEventData {
    #[prost(string, optional, tag = "1")]
    pub email: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub username: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "3")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventType {
    Unknown = 0,
    UserRegistered = 1,
    UserLogin = 2,
    UserLogout = 3,
}
impl EventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::UserRegistered => "USER_REGISTERED",
            Self::UserLogin => "USER_LOGIN",
            Self::UserLogout => "USER_LOGOUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "USER_REGISTERED" => Some(Self::UserRegistered),
            "USER_LOGIN" => Some(Self::UserLogin),
            "USER_LOGOUT" => Some(Self::UserLogout),
            _ => None,
        }
    }
}
