// This file is @generated by prost-build.
/// Voting mode for proposals
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VotingMode {
    /// Fast path - threshold-based, immediate execution
    Fast = 0,
    /// Slow path - majority voting with voting window
    Slow = 1,
}
impl VotingMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Fast => "VOTING_MODE_FAST",
            Self::Slow => "VOTING_MODE_SLOW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOTING_MODE_FAST" => Some(Self::Fast),
            "VOTING_MODE_SLOW" => Some(Self::Slow),
            _ => None,
        }
    }
}
/// Vote option for governance proposals
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProposalVoteOption {
    None = 0,
    Yes = 1,
    No = 2,
    Abstain = 3,
}
impl ProposalVoteOption {
    /// String value of the enum field names used in the ProtoBuf definition.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "VOTE_OPTION_NONE",
            Self::Yes => "VOTE_OPTION_YES",
            Self::No => "VOTE_OPTION_NO",
            Self::Abstain => "VOTE_OPTION_ABSTAIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOTE_OPTION_NONE" => Some(Self::None),
            "VOTE_OPTION_YES" => Some(Self::Yes),
            "VOTE_OPTION_NO" => Some(Self::No),
            "VOTE_OPTION_ABSTAIN" => Some(Self::Abstain),
            _ => None,
        }
    }
}
/// Type of action in a proposal, decoded from calldata function selector
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProposalActionType {
    Unknown = 0,
    AddMember = 1,
    RemoveMember = 2,
    AddEditor = 3,
    RemoveEditor = 4,
    Publish = 5,
    Flag = 6,
    Unflag = 7,
    UnflagEditor = 8,
    UpdateVotingSettings = 9,
    Ping = 10,
}
impl ProposalActionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "PROPOSAL_ACTION_UNKNOWN",
            Self::AddMember => "PROPOSAL_ACTION_ADD_MEMBER",
            Self::RemoveMember => "PROPOSAL_ACTION_REMOVE_MEMBER",
            Self::AddEditor => "PROPOSAL_ACTION_ADD_EDITOR",
            Self::RemoveEditor => "PROPOSAL_ACTION_REMOVE_EDITOR",
            Self::Publish => "PROPOSAL_ACTION_PUBLISH",
            Self::Flag => "PROPOSAL_ACTION_FLAG",
            Self::Unflag => "PROPOSAL_ACTION_UNFLAG",
            Self::UnflagEditor => "PROPOSAL_ACTION_UNFLAG_EDITOR",
            Self::UpdateVotingSettings => "PROPOSAL_ACTION_UPDATE_VOTING_SETTINGS",
            Self::Ping => "PROPOSAL_ACTION_PING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROPOSAL_ACTION_UNKNOWN" => Some(Self::Unknown),
            "PROPOSAL_ACTION_ADD_MEMBER" => Some(Self::AddMember),
            "PROPOSAL_ACTION_REMOVE_MEMBER" => Some(Self::RemoveMember),
            "PROPOSAL_ACTION_ADD_EDITOR" => Some(Self::AddEditor),
            "PROPOSAL_ACTION_REMOVE_EDITOR" => Some(Self::RemoveEditor),
            "PROPOSAL_ACTION_PUBLISH" => Some(Self::Publish),
            "PROPOSAL_ACTION_FLAG" => Some(Self::Flag),
            "PROPOSAL_ACTION_UNFLAG" => Some(Self::Unflag),
            "PROPOSAL_ACTION_UNFLAG_EDITOR" => Some(Self::UnflagEditor),
            "PROPOSAL_ACTION_UPDATE_VOTING_SETTINGS" => Some(Self::UpdateVotingSettings),
            "PROPOSAL_ACTION_PING" => Some(Self::Ping),
            _ => None,
        }
    }
}
/// Action to be executed when proposal passes (raw form)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalAction {
    /// 20 bytes - target contract address
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - uint256 ETH value to send
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// calldata (function selector + encoded args)
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// HermesProposalCreated - emitted for EACH action in a proposal
/// For proposals with multiple actions, multiple events are emitted with the same proposal_id
/// but different action_index values.
/// Data encoding: abi.encode(VotingMode, Action\[\])
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalCreated {
    /// 16 bytes - space creating the proposal
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - unique proposal identifier (from topic field)
    #[prost(bytes = "vec", tag = "2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// Fast or Slow path
    #[prost(enumeration = "VotingMode", tag = "3")]
    pub voting_mode: i32,
    /// Index of this action in the proposal (0-based)
    #[prost(uint32, tag = "4")]
    pub action_index: u32,
    /// Total number of actions in the proposal
    #[prost(uint32, tag = "5")]
    pub action_count: u32,
    /// Decoded action type from calldata selector
    #[prost(enumeration = "ProposalActionType", tag = "6")]
    pub action_type: i32,
    /// Raw action data (to, value, calldata)
    #[prost(message, optional, tag = "7")]
    pub action: ::core::option::Option<ProposalAction>,
    #[prost(message, optional, tag = "8")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesProposalVoted - emitted when a vote is cast on a proposal
/// Data encoding: abi.encode(bytes32(proposalId), VoteOption)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalVoted {
    /// 16 bytes - space casting the vote (from from_id)
    #[prost(bytes = "vec", tag = "1")]
    pub voter_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space that owns the proposal (from to_id)
    #[prost(bytes = "vec", tag = "2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - proposal being voted on (from topic field)
    #[prost(bytes = "vec", tag = "3")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// The vote cast
    #[prost(enumeration = "ProposalVoteOption", tag = "4")]
    pub vote: i32,
    #[prost(message, optional, tag = "5")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesProposalExecuted - emitted when a passed proposal is executed
/// Data encoding: abi.encode(bytes32(proposalId))
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalExecuted {
    /// 16 bytes - space executing the proposal
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - executed proposal identifier (from topic field)
    #[prost(bytes = "vec", tag = "2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
