// This file is @generated by prost-build.
/// Decoded action: add a member to the space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddMemberAction {
    /// 20 bytes - address to add as member
    #[prost(bytes = "vec", tag = "1")]
    pub target_address: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: remove a member from the space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveMemberAction {
    /// 20 bytes - address to remove
    #[prost(bytes = "vec", tag = "1")]
    pub target_address: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: add an editor to the space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddEditorAction {
    /// 20 bytes - address to add as editor
    #[prost(bytes = "vec", tag = "1")]
    pub target_address: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: remove an editor from the space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveEditorAction {
    /// 20 bytes - address to remove
    #[prost(bytes = "vec", tag = "1")]
    pub target_address: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: unflag an editor
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnflagEditorAction {
    /// 20 bytes - editor address to unflag
    #[prost(bytes = "vec", tag = "1")]
    pub target_address: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: publish content
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishAction {
    /// Content URI (IPFS hash)
    #[prost(string, tag = "1")]
    pub content_uri: ::prost::alloc::string::String,
    /// Edit metadata
    #[prost(bytes = "vec", tag = "2")]
    pub metadata: ::prost::alloc::vec::Vec<u8>,
    /// Edit name (extracted from IPFS cache)
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
/// Decoded action: flag content
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlagAction {
    /// Content identifier being flagged
    #[prost(bytes = "vec", tag = "1")]
    pub content_id: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: unflag content
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnflagAction {
    /// Content identifier being unflagged
    #[prost(bytes = "vec", tag = "1")]
    pub content_id: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: update voting settings (V2 — 7 fields matching contract VotingSettings)
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateVotingSettingsAction {
    /// Slow path late execution (0..RATIO_BASE)
    #[prost(uint64, tag = "5")]
    pub partial_percentage_support_threshold: u64,
    /// Slow path early execution (0..RATIO_BASE)
    #[prost(uint64, tag = "6")]
    pub universal_percentage_support_threshold: u64,
    /// Fast path absolute YES votes
    #[prost(uint64, tag = "7")]
    pub flat_support_threshold: u64,
    /// Minimum participating votes for slow path
    #[prost(uint64, tag = "8")]
    pub quorum: u64,
    /// Voting window duration in seconds
    #[prost(uint64, tag = "9")]
    pub duration: u64,
    /// Whether new members get fast-path access
    #[prost(bool, tag = "10")]
    pub disable_fast_path_access_for_new_members: bool,
    /// Seconds after lastDate that execution is allowed
    #[prost(uint64, tag = "11")]
    pub execution_grace_period: u64,
}
/// Decoded action: subspace edge operation (add/remove verified or related edge)
/// The specific operation type is determined by the ProposalActionType enum value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceEdgeAction {
    /// 16 bytes - target child space
    #[prost(bytes = "vec", tag = "1")]
    pub target_space_id: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: subspace topic operation (declare/remove topic)
/// The specific operation type is determined by the ProposalActionType enum value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceTopicAction {
    /// 16 bytes - topic entity ID
    #[prost(bytes = "vec", tag = "1")]
    pub target_topic_id: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: set the space topic
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetTopicAction {
    /// 16 bytes - topic entity ID
    #[prost(bytes = "vec", tag = "1")]
    pub target_topic_id: ::prost::alloc::vec::Vec<u8>,
}
/// Decoded action: unset the current space topic
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnsetTopicAction {
    /// 16 bytes - topic entity ID
    #[prost(bytes = "vec", tag = "1")]
    pub target_topic_id: ::prost::alloc::vec::Vec<u8>,
}
/// Action to be executed when proposal passes
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalAction {
    /// 20 bytes - target contract address
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - uint256 ETH value to send
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// calldata (function selector + encoded args)
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Decoded action (based on function selector in calldata)
    #[prost(
        oneof = "proposal_action::Action",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26"
    )]
    pub action: ::core::option::Option<proposal_action::Action>,
}
/// Nested message and enum types in `ProposalAction`.
pub mod proposal_action {
    /// Decoded action (based on function selector in calldata)
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Action {
        #[prost(message, tag = "10")]
        AddMember(super::AddMemberAction),
        #[prost(message, tag = "11")]
        RemoveMember(super::RemoveMemberAction),
        #[prost(message, tag = "12")]
        AddEditor(super::AddEditorAction),
        #[prost(message, tag = "13")]
        RemoveEditor(super::RemoveEditorAction),
        #[prost(message, tag = "14")]
        UnflagEditor(super::UnflagEditorAction),
        #[prost(message, tag = "15")]
        Publish(super::PublishAction),
        #[prost(message, tag = "16")]
        Flag(super::FlagAction),
        #[prost(message, tag = "17")]
        Unflag(super::UnflagAction),
        #[prost(message, tag = "18")]
        UpdateVotingSettings(super::UpdateVotingSettingsAction),
        #[prost(message, tag = "19")]
        SubspaceVerified(super::SubspaceEdgeAction),
        #[prost(message, tag = "20")]
        SubspaceUnverified(super::SubspaceEdgeAction),
        #[prost(message, tag = "21")]
        SubspaceRelated(super::SubspaceEdgeAction),
        #[prost(message, tag = "22")]
        SubspaceUnrelated(super::SubspaceEdgeAction),
        #[prost(message, tag = "23")]
        SubspaceTopicDeclared(super::SubspaceTopicAction),
        #[prost(message, tag = "24")]
        SubspaceTopicRemoved(super::SubspaceTopicAction),
        #[prost(message, tag = "25")]
        SetTopic(super::SetTopicAction),
        #[prost(message, tag = "26")]
        UnsetTopic(super::UnsetTopicAction),
    }
}
/// Voting settings for a proposal, from PROPOSAL_SETTINGS_SELECTED event.
/// V2 — 8 fields matching contract ProposalParameters, with per-proposal executeBy.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProposalSettings {
    /// Slow (0) or Fast (1)
    #[prost(enumeration = "VotingMode", tag = "7")]
    pub voting_mode: i32,
    /// Slow path late execution (0..RATIO_BASE)
    #[prost(uint64, tag = "8")]
    pub partial_percentage_support_threshold: u64,
    /// Slow path early execution (0..RATIO_BASE)
    #[prost(uint64, tag = "9")]
    pub universal_percentage_support_threshold: u64,
    /// Fast path absolute YES votes
    #[prost(uint64, tag = "10")]
    pub flat_support_threshold: u64,
    /// Minimum participating votes for slow path
    #[prost(uint64, tag = "11")]
    pub quorum: u64,
    /// Block timestamp when voting starts
    #[prost(uint64, tag = "12")]
    pub start_date: u64,
    /// Block timestamp when voting ends
    #[prost(uint64, tag = "13")]
    pub last_date: u64,
    /// Inclusive upper bound timestamp for execution
    #[prost(uint64, tag = "14")]
    pub execute_by: u64,
}
/// HermesProposalCreated - squashed from PROPOSAL_CREATED + PROPOSAL_SETTINGS_USED
/// Contains all actions in a single message with voting settings.
/// Data encoding: abi.encode(bytes16 proposalId, VotingMode, Action\[\])
/// Note: If PROPOSAL_SETTINGS_USED is missing, both events should be discarded with an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalCreated {
    /// 16 bytes - space owning the proposal (to_id)
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space creating the proposal (from_id)
    #[prost(bytes = "vec", tag = "2")]
    pub proposer_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - unique proposal identifier
    #[prost(bytes = "vec", tag = "3")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// Fast or Slow path
    #[prost(enumeration = "VotingMode", tag = "4")]
    pub voting_mode: i32,
    /// All actions in the proposal
    #[prost(message, repeated, tag = "5")]
    pub actions: ::prost::alloc::vec::Vec<ProposalAction>,
    /// Voting settings (from PROPOSAL_SETTINGS_USED)
    #[prost(message, optional, tag = "6")]
    pub settings: ::core::option::Option<ProposalSettings>,
    #[prost(message, optional, tag = "10")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesProposalUpdated - squashed from PROPOSAL_UPDATED + PROPOSAL_SETTINGS_USED
/// Contains all actions in a single message with voting settings.
/// Data encoding: abi.encode(bytes16 proposalId, VotingMode, Action\[\])
/// Note: If PROPOSAL_SETTINGS_USED is missing, both events should be discarded with an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalUpdated {
    /// 16 bytes - space owning the proposal (to_id)
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space updating the proposal (from_id)
    #[prost(bytes = "vec", tag = "2")]
    pub proposer_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - unique proposal identifier
    #[prost(bytes = "vec", tag = "3")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// Fast or Slow path
    #[prost(enumeration = "VotingMode", tag = "4")]
    pub voting_mode: i32,
    /// All actions in the proposal
    #[prost(message, repeated, tag = "5")]
    pub actions: ::prost::alloc::vec::Vec<ProposalAction>,
    /// Voting settings (from PROPOSAL_SETTINGS_USED)
    #[prost(message, optional, tag = "6")]
    pub settings: ::core::option::Option<ProposalSettings>,
    #[prost(message, optional, tag = "10")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesProposalVoted - emitted when a vote is cast on a proposal
/// Data encoding: abi.encode(bytes16 proposalId, uint8 proposalVersion, VoteOption)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalVoted {
    /// 16 bytes - space casting the vote (from from_id)
    #[prost(bytes = "vec", tag = "1")]
    pub voter_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space that owns the proposal (from to_id)
    #[prost(bytes = "vec", tag = "2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - proposal being voted on
    #[prost(bytes = "vec", tag = "3")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// The vote cast
    #[prost(enumeration = "ProposalVoteOption", tag = "4")]
    pub vote: i32,
    #[prost(message, optional, tag = "5")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
    /// Proposal version being voted on (uint8 on-chain)
    #[prost(uint32, tag = "6")]
    pub proposal_version: u32,
}
/// HermesProposalExecuted - emitted when a passed proposal is executed
/// Data encoding: abi.encode(bytes16 proposalId)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalExecuted {
    /// 16 bytes - space executing the proposal
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - executed proposal identifier
    #[prost(bytes = "vec", tag = "2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesProposalSettingsUpdated - emitted for orphaned PROPOSAL_SETTINGS_SELECTED events.
/// This occurs when a NO vote on a fast-path proposal escalates it to slow path:
/// the contract emits PROPOSAL_SETTINGS_SELECTED (via ping) with new settings but
/// does NOT emit PROPOSAL_UPDATED. The pipeline detects these orphaned settings and
/// emits them as a settings-only update so the indexer can update the proposal in place.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalSettingsUpdated {
    /// 16 bytes - space owning the proposal (from_id)
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - proposal identifier
    #[prost(bytes = "vec", tag = "2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// Updated voting settings
    #[prost(message, optional, tag = "3")]
    pub settings: ::core::option::Option<ProposalSettings>,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesVotingSettingsUpdated - emitted when DAO-global voting settings change.
/// Data encoding: abi.encode(VotingSettings) — the full 7-field V2 struct.
/// Subject topic is bytes32(0) since this is a space-level (not proposal-level) event.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesVotingSettingsUpdated {
    /// 16 bytes - space whose settings changed (from_id)
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// Slow path late execution threshold (0..RATIO_BASE)
    #[prost(uint64, tag = "2")]
    pub partial_percentage_support_threshold: u64,
    /// Slow path early execution threshold (0..RATIO_BASE)
    #[prost(uint64, tag = "3")]
    pub universal_percentage_support_threshold: u64,
    /// Fast path absolute YES votes needed
    #[prost(uint64, tag = "4")]
    pub flat_support_threshold: u64,
    /// Minimum participating votes for slow path
    #[prost(uint64, tag = "5")]
    pub quorum: u64,
    /// Voting window duration in seconds
    #[prost(uint64, tag = "6")]
    pub duration: u64,
    /// Whether newly added members get fast-path access
    #[prost(bool, tag = "7")]
    pub disable_fast_path_access_for_new_members: bool,
    /// Seconds after lastDate that execution is allowed
    #[prost(uint64, tag = "8")]
    pub execution_grace_period: u64,
    #[prost(message, optional, tag = "9")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// Voting mode for proposals
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VotingMode {
    /// Fast path - threshold-based, immediate execution
    Fast = 0,
    /// Slow path - majority voting with voting window
    Slow = 1,
}
impl VotingMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Fast => "VOTING_MODE_FAST",
            Self::Slow => "VOTING_MODE_SLOW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOTING_MODE_FAST" => Some(Self::Fast),
            "VOTING_MODE_SLOW" => Some(Self::Slow),
            _ => None,
        }
    }
}
/// Vote option for governance proposals
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProposalVoteOption {
    VoteOptionNone = 0,
    VoteOptionYes = 1,
    VoteOptionNo = 2,
    VoteOptionAbstain = 3,
}
impl ProposalVoteOption {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::VoteOptionNone => "VOTE_OPTION_NONE",
            Self::VoteOptionYes => "VOTE_OPTION_YES",
            Self::VoteOptionNo => "VOTE_OPTION_NO",
            Self::VoteOptionAbstain => "VOTE_OPTION_ABSTAIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOTE_OPTION_NONE" => Some(Self::VoteOptionNone),
            "VOTE_OPTION_YES" => Some(Self::VoteOptionYes),
            "VOTE_OPTION_NO" => Some(Self::VoteOptionNo),
            "VOTE_OPTION_ABSTAIN" => Some(Self::VoteOptionAbstain),
            _ => None,
        }
    }
}
/// Type of action in a proposal, decoded from calldata function selector
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProposalActionType {
    ProposalActionUnknown = 0,
    ProposalActionAddMember = 1,
    ProposalActionRemoveMember = 2,
    ProposalActionAddEditor = 3,
    ProposalActionRemoveEditor = 4,
    ProposalActionPublish = 5,
    ProposalActionFlag = 6,
    ProposalActionUnflag = 7,
    ProposalActionUnflagEditor = 8,
    ProposalActionUpdateVotingSettings = 9,
    ProposalActionSubspaceVerified = 11,
    ProposalActionSubspaceUnverified = 12,
    ProposalActionSubspaceRelated = 13,
    ProposalActionSubspaceUnrelated = 14,
    ProposalActionSubspaceTopicDeclared = 15,
    ProposalActionSubspaceTopicRemoved = 16,
    ProposalActionSetTopic = 17,
    ProposalActionUnsetTopic = 18,
}
impl ProposalActionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ProposalActionUnknown => "PROPOSAL_ACTION_UNKNOWN",
            Self::ProposalActionAddMember => "PROPOSAL_ACTION_ADD_MEMBER",
            Self::ProposalActionRemoveMember => "PROPOSAL_ACTION_REMOVE_MEMBER",
            Self::ProposalActionAddEditor => "PROPOSAL_ACTION_ADD_EDITOR",
            Self::ProposalActionRemoveEditor => "PROPOSAL_ACTION_REMOVE_EDITOR",
            Self::ProposalActionPublish => "PROPOSAL_ACTION_PUBLISH",
            Self::ProposalActionFlag => "PROPOSAL_ACTION_FLAG",
            Self::ProposalActionUnflag => "PROPOSAL_ACTION_UNFLAG",
            Self::ProposalActionUnflagEditor => "PROPOSAL_ACTION_UNFLAG_EDITOR",
            Self::ProposalActionUpdateVotingSettings => "PROPOSAL_ACTION_UPDATE_VOTING_SETTINGS",
            Self::ProposalActionSubspaceVerified => "PROPOSAL_ACTION_SUBSPACE_VERIFIED",
            Self::ProposalActionSubspaceUnverified => "PROPOSAL_ACTION_SUBSPACE_UNVERIFIED",
            Self::ProposalActionSubspaceRelated => "PROPOSAL_ACTION_SUBSPACE_RELATED",
            Self::ProposalActionSubspaceUnrelated => "PROPOSAL_ACTION_SUBSPACE_UNRELATED",
            Self::ProposalActionSubspaceTopicDeclared => "PROPOSAL_ACTION_SUBSPACE_TOPIC_DECLARED",
            Self::ProposalActionSubspaceTopicRemoved => "PROPOSAL_ACTION_SUBSPACE_TOPIC_REMOVED",
            Self::ProposalActionSetTopic => "PROPOSAL_ACTION_SET_TOPIC",
            Self::ProposalActionUnsetTopic => "PROPOSAL_ACTION_UNSET_TOPIC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROPOSAL_ACTION_UNKNOWN" => Some(Self::ProposalActionUnknown),
            "PROPOSAL_ACTION_ADD_MEMBER" => Some(Self::ProposalActionAddMember),
            "PROPOSAL_ACTION_REMOVE_MEMBER" => Some(Self::ProposalActionRemoveMember),
            "PROPOSAL_ACTION_ADD_EDITOR" => Some(Self::ProposalActionAddEditor),
            "PROPOSAL_ACTION_REMOVE_EDITOR" => Some(Self::ProposalActionRemoveEditor),
            "PROPOSAL_ACTION_PUBLISH" => Some(Self::ProposalActionPublish),
            "PROPOSAL_ACTION_FLAG" => Some(Self::ProposalActionFlag),
            "PROPOSAL_ACTION_UNFLAG" => Some(Self::ProposalActionUnflag),
            "PROPOSAL_ACTION_UNFLAG_EDITOR" => Some(Self::ProposalActionUnflagEditor),
            "PROPOSAL_ACTION_UPDATE_VOTING_SETTINGS" => {
                Some(Self::ProposalActionUpdateVotingSettings)
            }
            "PROPOSAL_ACTION_SUBSPACE_VERIFIED" => Some(Self::ProposalActionSubspaceVerified),
            "PROPOSAL_ACTION_SUBSPACE_UNVERIFIED" => Some(Self::ProposalActionSubspaceUnverified),
            "PROPOSAL_ACTION_SUBSPACE_RELATED" => Some(Self::ProposalActionSubspaceRelated),
            "PROPOSAL_ACTION_SUBSPACE_UNRELATED" => Some(Self::ProposalActionSubspaceUnrelated),
            "PROPOSAL_ACTION_SUBSPACE_TOPIC_DECLARED" => {
                Some(Self::ProposalActionSubspaceTopicDeclared)
            }
            "PROPOSAL_ACTION_SUBSPACE_TOPIC_REMOVED" => {
                Some(Self::ProposalActionSubspaceTopicRemoved)
            }
            "PROPOSAL_ACTION_SET_TOPIC" => Some(Self::ProposalActionSetTopic),
            "PROPOSAL_ACTION_UNSET_TOPIC" => Some(Self::ProposalActionUnsetTopic),
            _ => None,
        }
    }
}
