// This file is @generated by prost-build.
/// Action to be executed when proposal passes
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalAction {
    /// 20 bytes - target contract address
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - uint256 ETH value to send
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// calldata (function selector + encoded args)
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Decoded arguments (populated based on action type)
    /// For ADD_MEMBER, REMOVE_MEMBER, ADD_EDITOR, REMOVE_EDITOR, UNFLAG_EDITOR:
    ///
    /// 20 bytes - the address argument
    #[prost(bytes = "vec", tag = "4")]
    pub target_address: ::prost::alloc::vec::Vec<u8>,
}
/// Voting settings for a proposal, from PROPOSAL_SETTINGS_USED event
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProposalSettings {
    /// Block timestamp when voting starts
    #[prost(uint64, tag = "1")]
    pub start_date: u64,
    /// Block timestamp when voting ends
    #[prost(uint64, tag = "2")]
    pub last_date: u64,
    /// Slow (0) or Fast (1)
    #[prost(enumeration = "VotingMode", tag = "3")]
    pub voting_mode: i32,
    /// Minimum total votes for slow path
    #[prost(uint64, tag = "4")]
    pub quorum: u64,
    /// Fast path: absolute number of YES votes needed
    #[prost(uint64, tag = "5")]
    pub flat_threshold: u64,
    /// Slow path: percentage of RATIO_BASE (10,000,000)
    #[prost(uint64, tag = "6")]
    pub percentage_threshold: u64,
}
/// HermesProposalCreated - squashed from PROPOSAL_CREATED + PROPOSAL_SETTINGS_USED
/// Contains all actions in a single message with voting settings.
/// Data encoding: abi.encode(bytes16 proposalId, VotingMode, Action\[\])
/// Note: If PROPOSAL_SETTINGS_USED is missing, both events should be discarded with an error.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalCreated {
    /// 16 bytes - space owning the proposal (to_id)
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space creating the proposal (from_id)
    #[prost(bytes = "vec", tag = "2")]
    pub proposer_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - unique proposal identifier
    #[prost(bytes = "vec", tag = "3")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// Fast or Slow path
    #[prost(enumeration = "VotingMode", tag = "4")]
    pub voting_mode: i32,
    /// All actions in the proposal
    #[prost(message, repeated, tag = "5")]
    pub actions: ::prost::alloc::vec::Vec<ProposalAction>,
    /// Voting settings (from PROPOSAL_SETTINGS_USED)
    #[prost(message, optional, tag = "6")]
    pub settings: ::core::option::Option<ProposalSettings>,
    #[prost(message, optional, tag = "10")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesProposalVoted - emitted when a vote is cast on a proposal
/// Data encoding: abi.encode(bytes16 proposalId, VoteOption)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalVoted {
    /// 16 bytes - space casting the vote (from from_id)
    #[prost(bytes = "vec", tag = "1")]
    pub voter_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space that owns the proposal (from to_id)
    #[prost(bytes = "vec", tag = "2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - proposal being voted on
    #[prost(bytes = "vec", tag = "3")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// The vote cast
    #[prost(enumeration = "ProposalVoteOption", tag = "4")]
    pub vote: i32,
    #[prost(message, optional, tag = "5")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesProposalExecuted - emitted when a passed proposal is executed
/// Data encoding: abi.encode(bytes16 proposalId)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesProposalExecuted {
    /// 16 bytes - space executing the proposal
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - executed proposal identifier
    #[prost(bytes = "vec", tag = "2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// Voting mode for proposals
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VotingMode {
    /// Fast path - threshold-based, immediate execution
    Fast = 0,
    /// Slow path - majority voting with voting window
    Slow = 1,
}
impl VotingMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Fast => "VOTING_MODE_FAST",
            Self::Slow => "VOTING_MODE_SLOW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOTING_MODE_FAST" => Some(Self::Fast),
            "VOTING_MODE_SLOW" => Some(Self::Slow),
            _ => None,
        }
    }
}
/// Vote option for governance proposals
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProposalVoteOption {
    VoteOptionNone = 0,
    VoteOptionYes = 1,
    VoteOptionNo = 2,
    VoteOptionAbstain = 3,
}
impl ProposalVoteOption {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::VoteOptionNone => "VOTE_OPTION_NONE",
            Self::VoteOptionYes => "VOTE_OPTION_YES",
            Self::VoteOptionNo => "VOTE_OPTION_NO",
            Self::VoteOptionAbstain => "VOTE_OPTION_ABSTAIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOTE_OPTION_NONE" => Some(Self::VoteOptionNone),
            "VOTE_OPTION_YES" => Some(Self::VoteOptionYes),
            "VOTE_OPTION_NO" => Some(Self::VoteOptionNo),
            "VOTE_OPTION_ABSTAIN" => Some(Self::VoteOptionAbstain),
            _ => None,
        }
    }
}
/// Type of action in a proposal, decoded from calldata function selector
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProposalActionType {
    ProposalActionUnknown = 0,
    ProposalActionAddMember = 1,
    ProposalActionRemoveMember = 2,
    ProposalActionAddEditor = 3,
    ProposalActionRemoveEditor = 4,
    ProposalActionPublish = 5,
    ProposalActionFlag = 6,
    ProposalActionUnflag = 7,
    ProposalActionUnflagEditor = 8,
    ProposalActionUpdateVotingSettings = 9,
    ProposalActionPing = 10,
}
impl ProposalActionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ProposalActionUnknown => "PROPOSAL_ACTION_UNKNOWN",
            Self::ProposalActionAddMember => "PROPOSAL_ACTION_ADD_MEMBER",
            Self::ProposalActionRemoveMember => "PROPOSAL_ACTION_REMOVE_MEMBER",
            Self::ProposalActionAddEditor => "PROPOSAL_ACTION_ADD_EDITOR",
            Self::ProposalActionRemoveEditor => "PROPOSAL_ACTION_REMOVE_EDITOR",
            Self::ProposalActionPublish => "PROPOSAL_ACTION_PUBLISH",
            Self::ProposalActionFlag => "PROPOSAL_ACTION_FLAG",
            Self::ProposalActionUnflag => "PROPOSAL_ACTION_UNFLAG",
            Self::ProposalActionUnflagEditor => "PROPOSAL_ACTION_UNFLAG_EDITOR",
            Self::ProposalActionUpdateVotingSettings => {
                "PROPOSAL_ACTION_UPDATE_VOTING_SETTINGS"
            }
            Self::ProposalActionPing => "PROPOSAL_ACTION_PING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROPOSAL_ACTION_UNKNOWN" => Some(Self::ProposalActionUnknown),
            "PROPOSAL_ACTION_ADD_MEMBER" => Some(Self::ProposalActionAddMember),
            "PROPOSAL_ACTION_REMOVE_MEMBER" => Some(Self::ProposalActionRemoveMember),
            "PROPOSAL_ACTION_ADD_EDITOR" => Some(Self::ProposalActionAddEditor),
            "PROPOSAL_ACTION_REMOVE_EDITOR" => Some(Self::ProposalActionRemoveEditor),
            "PROPOSAL_ACTION_PUBLISH" => Some(Self::ProposalActionPublish),
            "PROPOSAL_ACTION_FLAG" => Some(Self::ProposalActionFlag),
            "PROPOSAL_ACTION_UNFLAG" => Some(Self::ProposalActionUnflag),
            "PROPOSAL_ACTION_UNFLAG_EDITOR" => Some(Self::ProposalActionUnflagEditor),
            "PROPOSAL_ACTION_UPDATE_VOTING_SETTINGS" => {
                Some(Self::ProposalActionUpdateVotingSettings)
            }
            "PROPOSAL_ACTION_PING" => Some(Self::ProposalActionPing),
            _ => None,
        }
    }
}
