// This file is @generated by prost-build.
/// *
/// November 13, 2025
/// A HermesEdit represents a GRC-20 Edit that has been enriched by the
/// Hermes event stream service. Hermes currently does a few things:
///
/// 1. Resolves the IPFS CID into the serialized edit representation
/// 2. Appends any blockchain metadata useful for downstream consumers
/// 3. Appends any community or space topology metadata useful for
///     downstream consumers
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesEdit {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub ops: ::prost::alloc::vec::Vec<::wire::pb::grc20::Op>,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub authors: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "5")]
    pub language: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Space Topology metadata
    #[prost(string, tag = "6")]
    pub space_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_canonical: bool,
    /// Blockchain Metadata
    ///
    /// Unix timestamp in seconds
    #[prost(uint64, tag = "8")]
    pub created_at: u64,
    /// address
    #[prost(bytes = "vec", tag = "9")]
    pub created_by: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "10")]
    pub block_number: u64,
    #[prost(string, tag = "11")]
    pub cursor: ::prost::alloc::string::String,
}
