// This file is @generated by prost-build.
/// Role types for membership changes
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MembershipRole {
    Editor = 0,
    Member = 1,
}
impl MembershipRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Editor => "EDITOR",
            Self::Member => "MEMBER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EDITOR" => Some(Self::Editor),
            "MEMBER" => Some(Self::Member),
            _ => None,
        }
    }
}
/// HermesRoleGranted - editor or member added to a space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesRoleGranted {
    /// 16 bytes - space granting role
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - address receiving role
    #[prost(bytes = "vec", tag = "2")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    /// EDITOR or MEMBER
    #[prost(enumeration = "MembershipRole", tag = "3")]
    pub role: i32,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesRoleRevoked - editor or member removed from a space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesRoleRevoked {
    /// 16 bytes - space revoking role
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - address losing role
    #[prost(bytes = "vec", tag = "2")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    /// EDITOR or MEMBER
    #[prost(enumeration = "MembershipRole", tag = "3")]
    pub role: i32,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesSpaceLeft - member voluntarily left a space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesSpaceLeft {
    /// 16 bytes - member's space ID
    #[prost(bytes = "vec", tag = "1")]
    pub member_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space being left
    #[prost(bytes = "vec", tag = "2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
