// This file is @generated by prost-build.
/// HermesEditorFlagged - editor restricted from fast path
/// ZC16: topic = bytes32(editorSpaceId), data = abi.encode(editorAddress)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesEditorFlagged {
    /// 16 bytes - DAO space where action occurs (from_id)
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - editor's account address (from data)
    #[prost(bytes = "vec", tag = "2")]
    pub editor_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
    /// 16 bytes - editor's space ID (from topic)
    #[prost(bytes = "vec", tag = "4")]
    pub editor_space_id: ::prost::alloc::vec::Vec<u8>,
}
/// HermesEditorUnflagged - editor unrestricted from fast path
/// ZC16: topic = bytes32(editorSpaceId), data = abi.encode(editorAddress)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesEditorUnflagged {
    /// 16 bytes - DAO space where action occurs (from_id)
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - editor's account address (from data)
    #[prost(bytes = "vec", tag = "2")]
    pub editor_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
    /// 16 bytes - editor's space ID (from topic)
    #[prost(bytes = "vec", tag = "4")]
    pub editor_space_id: ::prost::alloc::vec::Vec<u8>,
}
/// HermesContentFlagged - content flagged by a space
/// Topic field: bytes32(TOPIC_UUID) - optional
/// Data encoding: abi.encode(bytes(flaggedUri))
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesContentFlagged {
    /// 16 bytes - space flagging content
    #[prost(bytes = "vec", tag = "1")]
    pub flagger_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space whose content is flagged
    #[prost(bytes = "vec", tag = "2")]
    pub target_space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - optional topic UUID
    #[prost(bytes = "vec", tag = "3")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
    /// Decoded URI of flagged content
    #[prost(string, tag = "4")]
    pub uri: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesContentUnflagged - content unflagged by a space
/// Topic field: bytes32(TOPIC_UUID) - optional
/// Data encoding: abi.encode(bytes(unflaggedUri))
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesContentUnflagged {
    /// 16 bytes - space unflagging content
    #[prost(bytes = "vec", tag = "1")]
    pub unflagger_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space whose content is unflagged
    #[prost(bytes = "vec", tag = "2")]
    pub target_space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - optional topic UUID
    #[prost(bytes = "vec", tag = "3")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
    /// Decoded URI of unflagged content
    #[prost(string, tag = "4")]
    pub uri: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
