// This file is @generated by prost-build.
/// HermesEditorFlagged - editor flagged within a space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesEditorFlagged {
    /// 16 bytes - space containing editor
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - flagged editor address
    #[prost(bytes = "vec", tag = "2")]
    pub editor_account: ::prost::alloc::vec::Vec<u8>,
    /// Flag details/reason
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesEditorUnflagged - editor unflagged within a space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesEditorUnflagged {
    /// 16 bytes - space containing editor
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - unflagged editor address
    #[prost(bytes = "vec", tag = "2")]
    pub editor_account: ::prost::alloc::vec::Vec<u8>,
    /// Unflag details
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesContentFlagged - content flagged by a space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesContentFlagged {
    /// 16 bytes - space flagging content
    #[prost(bytes = "vec", tag = "1")]
    pub flagger_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space whose content is flagged
    #[prost(bytes = "vec", tag = "2")]
    pub target_space_id: ::prost::alloc::vec::Vec<u8>,
    /// Flag details (entity type, ID, reason)
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// HermesContentUnflagged - content unflagged by a space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesContentUnflagged {
    /// 16 bytes - space unflagging content
    #[prost(bytes = "vec", tag = "1")]
    pub unflagger_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space whose content is unflagged
    #[prost(bytes = "vec", tag = "2")]
    pub target_space_id: ::prost::alloc::vec::Vec<u8>,
    /// Unflag details
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
