// This file is @generated by prost-build.
/// Score update for an entity (global score)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntityScore {
    /// 16 bytes UUID
    #[prost(bytes = "vec", tag = "1")]
    pub entity_id: ::prost::alloc::vec::Vec<u8>,
    /// Normalized score
    #[prost(double, tag = "2")]
    pub score: f64,
    /// Unix timestamp in seconds
    #[prost(uint64, tag = "3")]
    pub updated_at: u64,
}
/// Score update for a perspective (local score within a space)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PerspectiveScore {
    /// 16 bytes UUID
    #[prost(bytes = "vec", tag = "1")]
    pub entity_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes UUID
    #[prost(bytes = "vec", tag = "2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// Normalized score
    #[prost(double, tag = "3")]
    pub score: f64,
    /// Unix timestamp in seconds
    #[prost(uint64, tag = "4")]
    pub updated_at: u64,
}
/// Score update for a space
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceScore {
    /// 16 bytes UUID
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// Space score
    #[prost(double, tag = "2")]
    pub score: f64,
    /// Unix timestamp in seconds
    #[prost(uint64, tag = "3")]
    pub updated_at: u64,
}
/// Batch of score updates published by scoring service
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesScoresBatch {
    #[prost(message, repeated, tag = "1")]
    pub entity_scores: ::prost::alloc::vec::Vec<EntityScore>,
    #[prost(message, repeated, tag = "2")]
    pub perspective_scores: ::prost::alloc::vec::Vec<PerspectiveScore>,
    #[prost(message, repeated, tag = "3")]
    pub space_scores: ::prost::alloc::vec::Vec<SpaceScore>,
    /// When scores were computed - Unix timestamp in seconds
    #[prost(uint64, tag = "4")]
    pub computed_at: u64,
    /// Sequence number within run
    #[prost(uint32, tag = "5")]
    pub batch_sequence: u32,
    /// True for last batch in run
    #[prost(bool, tag = "6")]
    pub is_final: bool,
}
