// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PersonalSpacePayload {
    #[prost(bytes = "vec", tag = "1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DefaultDaoSpacePayload {
    /// uuids
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub initial_editors: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// uuids
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub initial_members: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesCreateSpace {
    /// uuid
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// uuid
    #[prost(bytes = "vec", tag = "2")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
    /// Blockchain Metadata
    ///
    /// Unix timestamp in seconds
    #[prost(uint64, tag = "5")]
    pub created_at: u64,
    /// address
    #[prost(bytes = "vec", tag = "6")]
    pub created_by: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "7")]
    pub block_number: u64,
    #[prost(string, tag = "8")]
    pub cursor: ::prost::alloc::string::String,
    #[prost(oneof = "hermes_create_space::Payload", tags = "3, 4")]
    pub payload: ::core::option::Option<hermes_create_space::Payload>,
}
/// Nested message and enum types in `HermesCreateSpace`.
pub mod hermes_create_space {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "3")]
        PersonalSpace(super::PersonalSpacePayload),
        #[prost(message, tag = "4")]
        DefaultDaoSpace(super::DefaultDaoSpacePayload),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SpaceType {
    Default = 0,
    Personal = 1,
}
impl SpaceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Default => "DEFAULT",
            Self::Personal => "PERSONAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEFAULT" => Some(Self::Default),
            "PERSONAL" => Some(Self::Personal),
            _ => None,
        }
    }
}
