// This file is @generated by prost-build.
/// HermesTopicDeclared - space declares a new topic
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesTopicDeclared {
    /// 16 bytes - space declaring topic
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - keccak256 of topic name
    #[prost(bytes = "vec", tag = "2")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
    /// Topic metadata (name, description)
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
