// This file is @generated by prost-build.
/// Emitted when the canonical graph changes.
/// The canonical graph represents the "trusted" portion of the topology,
/// where trust flows only through explicit edges (Verified, Related).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CanonicalGraphUpdated {
    /// Root space this graph was computed from
    #[prost(bytes = "vec", tag = "1")]
    pub root_id: ::prost::alloc::vec::Vec<u8>,
    /// Tree representation with edge metadata.
    /// The tree structure preserves distance from root, which matters
    /// for downstream consumers.
    #[prost(message, optional, tag = "2")]
    pub tree: ::core::option::Option<CanonicalTreeNode>,
    /// Flat set of all canonical space IDs.
    /// Useful for quick membership checks without traversing the tree.
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub canonical_space_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Block metadata from the event that triggered this update
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// A node in the canonical tree.
/// Represents a space and how it was reached from its parent.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CanonicalTreeNode {
    /// The space this node represents
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// How this node was reached from its parent
    #[prost(enumeration = "EdgeType", tag = "2")]
    pub edge_type: i32,
    /// If reached via topic edge, which topic (otherwise empty).
    /// Only set when edge_type is EDGE_TYPE_TOPIC.
    #[prost(bytes = "vec", tag = "3")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
    /// Children of this node in the traversal
    #[prost(message, repeated, tag = "4")]
    pub children: ::prost::alloc::vec::Vec<CanonicalTreeNode>,
}
/// The type of edge connecting a node to its parent in the tree.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EdgeType {
    /// Default value, should not appear in valid messages
    Unspecified = 0,
    /// Root node has no incoming edge
    Root = 1,
    /// Verified trust relationship (explicit edge)
    Verified = 2,
    /// Related trust relationship (explicit edge)
    Related = 3,
    /// Topic-based membership (resolved from SubtopicExtension)
    Topic = 4,
}
impl EdgeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EDGE_TYPE_UNSPECIFIED",
            Self::Root => "EDGE_TYPE_ROOT",
            Self::Verified => "EDGE_TYPE_VERIFIED",
            Self::Related => "EDGE_TYPE_RELATED",
            Self::Topic => "EDGE_TYPE_TOPIC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EDGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "EDGE_TYPE_ROOT" => Some(Self::Root),
            "EDGE_TYPE_VERIFIED" => Some(Self::Verified),
            "EDGE_TYPE_RELATED" => Some(Self::Related),
            "EDGE_TYPE_TOPIC" => Some(Self::Topic),
            _ => None,
        }
    }
}
