// This file is @generated by prost-build.
/// Emitted when the canonical graph changes.
/// The canonical graph represents the "trusted" portion of the topology,
/// where trust flows only through explicit edges (Verified, Related).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CanonicalGraphUpdated {
    /// Root space this graph was computed from
    #[prost(bytes = "vec", tag = "1")]
    pub root_id: ::prost::alloc::vec::Vec<u8>,
    /// Tree representation with edge metadata.
    /// The tree structure preserves distance from root, which matters
    /// for downstream consumers.
    #[prost(message, optional, tag = "2")]
    pub tree: ::core::option::Option<CanonicalTreeNode>,
    /// Flat set of all canonical space IDs.
    /// Useful for quick membership checks without traversing the tree.
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub canonical_space_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Block metadata from the event that triggered this update
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
/// A node in the canonical tree.
/// Represents a space and how it was reached from its parent.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CanonicalTreeNode {
    /// The space this node represents
    #[prost(bytes = "vec", tag = "1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// Children of this node in the traversal
    #[prost(message, repeated, tag = "6")]
    pub children: ::prost::alloc::vec::Vec<CanonicalTreeNode>,
    /// How this node was reached from its parent.
    /// Uses oneof to enforce that topic_id is only present for topic edges.
    #[prost(oneof = "canonical_tree_node::Edge", tags = "2, 3, 4, 5")]
    pub edge: ::core::option::Option<canonical_tree_node::Edge>,
}
/// Nested message and enum types in `CanonicalTreeNode`.
pub mod canonical_tree_node {
    /// How this node was reached from its parent.
    /// Uses oneof to enforce that topic_id is only present for topic edges.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Edge {
        /// Root node has no incoming edge
        #[prost(message, tag = "2")]
        Root(super::RootEdge),
        /// Verified trust relationship (explicit edge)
        #[prost(message, tag = "3")]
        Verified(super::VerifiedEdge),
        /// Related trust relationship (explicit edge)
        #[prost(message, tag = "4")]
        Related(super::RelatedEdge),
        /// Topic-based membership (resolved from SubtopicExtension)
        #[prost(message, tag = "5")]
        Topic(super::TopicEdge),
    }
}
/// Root node edge - no additional data needed
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RootEdge {}
/// Verified trust relationship edge - no additional data needed
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VerifiedEdge {}
/// Related trust relationship edge - no additional data needed
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RelatedEdge {}
/// Topic-based membership edge - includes the topic ID
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicEdge {
    /// The topic through which this space was reached
    #[prost(bytes = "vec", tag = "1")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
}
