// This file is @generated by prost-build.
/// Vote direction
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VoteDirection {
    Up = 0,
    Down = 1,
    /// For unvote
    None = 2,
}
impl VoteDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Up => "UP",
            Self::Down => "DOWN",
            Self::None => "NONE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UP" => Some(Self::Up),
            "DOWN" => Some(Self::Down),
            "NONE" => Some(Self::None),
            _ => None,
        }
    }
}
/// HermesVoteCast - vote cast on an object
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesVoteCast {
    /// 16 bytes - voter's space ID
    #[prost(bytes = "vec", tag = "1")]
    pub voter_id: ::prost::alloc::vec::Vec<u8>,
    /// 4 bytes - type discriminator
    #[prost(bytes = "vec", tag = "2")]
    pub object_type: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - object being voted on
    #[prost(bytes = "vec", tag = "3")]
    pub object_id: ::prost::alloc::vec::Vec<u8>,
    /// UP, DOWN, or NONE (unvote)
    #[prost(enumeration = "VoteDirection", tag = "4")]
    pub direction: i32,
    /// Additional vote data
    #[prost(bytes = "vec", tag = "5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "6")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
}
