// This file is @generated by prost-build.
/// HermesVoteCast - a response cast on an object
/// Topic encoding: bytes32(bytes4(objectType) << 224) | (bytes16(objectId) << 96)
/// Data encoding: abi.encode(uint16(version), bytes16(groupId), bytes16(spacePOV))
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HermesVoteCast {
    /// 16 bytes - voter's space ID
    #[prost(bytes = "vec", tag = "1")]
    pub voter_id: ::prost::alloc::vec::Vec<u8>,
    /// 4 bytes - type discriminator
    #[prost(bytes = "vec", tag = "2")]
    pub object_type: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - object being voted on
    #[prost(bytes = "vec", tag = "3")]
    pub object_id: ::prost::alloc::vec::Vec<u8>,
    /// UP, DOWN, or NONE (clear)
    #[prost(enumeration = "VoteDirection", tag = "4")]
    pub direction: i32,
    /// Vote format version (uint16 stored as uint32)
    #[prost(uint32, tag = "5")]
    pub version: u32,
    /// 16 bytes - group identifier
    #[prost(bytes = "vec", tag = "6")]
    pub group_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space point of view
    #[prost(bytes = "vec", tag = "7")]
    pub space_pov: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "8")]
    pub meta: ::core::option::Option<super::blockchain_metadata::BlockchainMetadata>,
    /// curation / stance / veracity
    #[prost(enumeration = "VoteKind", tag = "9")]
    pub kind: i32,
}
/// Vote direction for permissionless voting.
/// Direction is now a pure positive/negative/clear axis; which *kind* of response
/// it applies to is carried separately by VoteKind.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VoteDirection {
    Up = 0,
    Down = 1,
    /// For unvote
    None = 2,
}
impl VoteDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Up => "VOTE_DIRECTION_UP",
            Self::Down => "VOTE_DIRECTION_DOWN",
            Self::None => "VOTE_DIRECTION_NONE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOTE_DIRECTION_UP" => Some(Self::Up),
            "VOTE_DIRECTION_DOWN" => Some(Self::Down),
            "VOTE_DIRECTION_NONE" => Some(Self::None),
            _ => None,
        }
    }
}
/// Response kind — the axis a response applies to.
///
/// The three axes are independent: a user can simultaneously hold a curation
/// vote, a stance and a veracity response on the same object, and casting one
/// never touches another. The on-chain action hash is the only discriminator
/// (topic and data encoding are identical across kinds), so this field is the
/// decoded form of "which of the nine action hashes produced this event".
///
/// CURATION is 0 so that events produced before this field existed — and rows
/// written by the pre-vote_kind indexer — decode as curation, which is what
/// they are.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VoteKind {
    /// upvote / downvote / unvote
    Curation = 0,
    /// agree / disagree / unagree
    Stance = 1,
    /// verify / dispute / unverify
    Veracity = 2,
}
impl VoteKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Curation => "VOTE_KIND_CURATION",
            Self::Stance => "VOTE_KIND_STANCE",
            Self::Veracity => "VOTE_KIND_VERACITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VOTE_KIND_CURATION" => Some(Self::Curation),
            "VOTE_KIND_STANCE" => Some(Self::Stance),
            "VOTE_KIND_VERACITY" => Some(Self::Veracity),
            _ => None,
        }
    }
}
