// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Edit {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub ops: ::prost::alloc::vec::Vec<super::common::Op>,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub authors: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "5")]
    pub language: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImportEdit {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub ops: ::prost::alloc::vec::Vec<super::common::Op>,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub authors: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "5")]
    pub created_by: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "6")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "7")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "8")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "9")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Import {
    /// these strings are IPFS cids representing the import edit message
    #[prost(string, repeated, tag = "1")]
    pub edits: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct File {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(oneof = "file::Payload", tags = "2, 3, 4")]
    pub payload: ::core::option::Option<file::Payload>,
}
/// Nested message and enum types in `File`.
pub mod file {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "2")]
        AddEdit(super::Edit),
        #[prost(message, tag = "3")]
        ImportSpace(super::Import),
        #[prost(bytes, tag = "4")]
        ArchiveSpace(::prost::alloc::vec::Vec<u8>),
    }
}
