// @generated
// This file is @generated by prost-build.
// =============================================================================
// Raw Action - for consumers who want full control
// =============================================================================

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Action {
    /// 16 bytes - source space ID
    #[prost(bytes="vec", tag="1")]
    pub from_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - target space ID
    #[prost(bytes="vec", tag="2")]
    pub to_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - keccak256 hash of action name
    #[prost(bytes="vec", tag="3")]
    pub action: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - context-dependent (address, proposalId, topicId, etc.)
    #[prost(bytes="vec", tag="4")]
    pub topic: ::prost::alloc::vec::Vec<u8>,
    /// variable - action-specific payload
    #[prost(bytes="vec", tag="5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Actions {
    #[prost(message, repeated, tag="1")]
    pub actions: ::prost::alloc::vec::Vec<Action>,
}
// =============================================================================
// Governance Events - pre-filtered typed events
// =============================================================================

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceRegistered {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub space_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceRegisteredList {
    #[prost(message, repeated, tag="1")]
    pub spaces: ::prost::alloc::vec::Vec<SpaceRegistered>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceMigrated {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub new_space_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceMigratedList {
    #[prost(message, repeated, tag="1")]
    pub spaces: ::prost::alloc::vec::Vec<SpaceMigrated>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalCreated {
    /// 16 bytes - space creating proposal
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// Proposal metadata
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalCreatedList {
    #[prost(message, repeated, tag="1")]
    pub proposals: ::prost::alloc::vec::Vec<ProposalCreated>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalVoted {
    /// 16 bytes - voter space
    #[prost(bytes="vec", tag="1")]
    pub voter_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - proposal's space
    #[prost(bytes="vec", tag="2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - from topic field
    #[prost(bytes="vec", tag="3")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// Vote choice
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalVotedList {
    #[prost(message, repeated, tag="1")]
    pub votes: ::prost::alloc::vec::Vec<ProposalVoted>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalExecuted {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalExecutedList {
    #[prost(message, repeated, tag="1")]
    pub proposals: ::prost::alloc::vec::Vec<ProposalExecuted>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditorAdded {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub editor_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditorAddedList {
    #[prost(message, repeated, tag="1")]
    pub editors: ::prost::alloc::vec::Vec<EditorAdded>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditorRemoved {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub editor_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditorRemovedList {
    #[prost(message, repeated, tag="1")]
    pub editors: ::prost::alloc::vec::Vec<EditorRemoved>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberAdded {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub member_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberAddedList {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<MemberAdded>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberRemoved {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub member_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemberRemovedList {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<MemberRemoved>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditorFlagged {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub editor_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditorFlaggedList {
    #[prost(message, repeated, tag="1")]
    pub editors: ::prost::alloc::vec::Vec<EditorFlagged>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditorUnflagged {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub editor_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditorUnflaggedList {
    #[prost(message, repeated, tag="1")]
    pub editors: ::prost::alloc::vec::Vec<EditorUnflagged>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceLeft {
    /// 16 bytes - member leaving
    #[prost(bytes="vec", tag="1")]
    pub member_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space being left
    #[prost(bytes="vec", tag="2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceLeftList {
    #[prost(message, repeated, tag="1")]
    pub spaces: ::prost::alloc::vec::Vec<SpaceLeft>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicDeclared {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - keccak256 of topic name
    #[prost(bytes="vec", tag="2")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicDeclaredList {
    #[prost(message, repeated, tag="1")]
    pub topics: ::prost::alloc::vec::Vec<TopicDeclared>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditsPublished {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// Raw ABI-encoded data from event
    #[prost(bytes="vec", tag="2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Parsed IPFS URI (ipfs://Qm... or ipfs://bafy...), empty if invalid
    #[prost(string, tag="3")]
    pub content_uri: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditsPublishedList {
    #[prost(message, repeated, tag="1")]
    pub edits: ::prost::alloc::vec::Vec<EditsPublished>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flagged {
    /// 16 bytes - space flagging content
    #[prost(bytes="vec", tag="1")]
    pub flagger_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space being flagged
    #[prost(bytes="vec", tag="2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// Flag details
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlaggedList {
    #[prost(message, repeated, tag="1")]
    pub flags: ::prost::alloc::vec::Vec<Flagged>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Unflagged {
    /// 16 bytes - space unflagging content
    #[prost(bytes="vec", tag="1")]
    pub unflagger_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - space being unflagged
    #[prost(bytes="vec", tag="2")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// Unflag details
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnflaggedList {
    #[prost(message, repeated, tag="1")]
    pub unflags: ::prost::alloc::vec::Vec<Unflagged>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceRemoved {
    /// 16 bytes - parent space
    #[prost(bytes="vec", tag="1")]
    pub parent_space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub subspace_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceRemovedList {
    #[prost(message, repeated, tag="1")]
    pub subspaces: ::prost::alloc::vec::Vec<SubspaceRemoved>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceVerified {
    /// 16 bytes - parent space
    #[prost(bytes="vec", tag="1")]
    pub parent_space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub subspace_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceVerifiedList {
    #[prost(message, repeated, tag="1")]
    pub subspaces: ::prost::alloc::vec::Vec<SubspaceVerified>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceRelated {
    /// 16 bytes - parent space
    #[prost(bytes="vec", tag="1")]
    pub parent_space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub subspace_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceRelatedList {
    #[prost(message, repeated, tag="1")]
    pub subspaces: ::prost::alloc::vec::Vec<SubspaceRelated>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceTopicDeclared {
    /// 16 bytes - parent space
    #[prost(bytes="vec", tag="1")]
    pub parent_space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - from topic field (first 16 bytes)
    #[prost(bytes="vec", tag="2")]
    pub subspace_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - from topic field (last 16 bytes)
    #[prost(bytes="vec", tag="3")]
    pub topic_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubspaceTopicDeclaredList {
    #[prost(message, repeated, tag="1")]
    pub declarations: ::prost::alloc::vec::Vec<SubspaceTopicDeclared>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceTypeDeclared {
    /// 16 bytes - from both from_id and to_id (same)
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes - from topic field (e.g., keccak256("DAO_SPACE"))
    #[prost(bytes="vec", tag="2")]
    pub space_type: ::prost::alloc::vec::Vec<u8>,
    /// variable - from data field (e.g., "1.0.0" encoded)
    #[prost(bytes="vec", tag="3")]
    pub version: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceTypeDeclaredList {
    #[prost(message, repeated, tag="1")]
    pub declarations: ::prost::alloc::vec::Vec<SpaceTypeDeclared>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceCleared {
    /// 16 bytes - from from_id
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 20 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub space_address: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpaceClearedList {
    #[prost(message, repeated, tag="1")]
    pub spaces: ::prost::alloc::vec::Vec<SpaceCleared>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalSettingsUsed {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - from topic field (bytes16 padded to 32)
    #[prost(bytes="vec", tag="2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// abi.encode(startDate, lastDate, votingMode, quorum, supportThreshold)
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalSettingsUsedList {
    #[prost(message, repeated, tag="1")]
    pub settings: ::prost::alloc::vec::Vec<ProposalSettingsUsed>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalUpdated {
    /// 16 bytes
    #[prost(bytes="vec", tag="1")]
    pub space_id: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes - from topic field
    #[prost(bytes="vec", tag="2")]
    pub proposal_id: ::prost::alloc::vec::Vec<u8>,
    /// abi.encode(bytes16, VotingMode, Action\[\])
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalUpdatedList {
    #[prost(message, repeated, tag="1")]
    pub proposals: ::prost::alloc::vec::Vec<ProposalUpdated>,
}
// =============================================================================
// Permissionless Events
// =============================================================================

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectVoted {
    /// 16 bytes - voter space
    #[prost(bytes="vec", tag="1")]
    pub voter_id: ::prost::alloc::vec::Vec<u8>,
    /// 4 bytes
    #[prost(bytes="vec", tag="2")]
    pub object_type: ::prost::alloc::vec::Vec<u8>,
    /// 16 bytes
    #[prost(bytes="vec", tag="3")]
    pub object_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectUpvotedList {
    #[prost(message, repeated, tag="1")]
    pub votes: ::prost::alloc::vec::Vec<ObjectVoted>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectDownvotedList {
    #[prost(message, repeated, tag="1")]
    pub votes: ::prost::alloc::vec::Vec<ObjectVoted>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectUnvotedList {
    #[prost(message, repeated, tag="1")]
    pub votes: ::prost::alloc::vec::Vec<ObjectVoted>,
}
// @@protoc_insertion_point(module)
