# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscoring.proto\x12\x07scoring\"C\n\x0b\x45ntityScore\x12\x11\n\tentity_id\x18\x01 \x01(\x0c\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x12\n\nupdated_at\x18\x03 \x01(\x04\"Z\n\x10PerspectiveScore\x12\x11\n\tentity_id\x18\x01 \x01(\x0c\x12\x10\n\x08space_id\x18\x02 \x01(\x0c\x12\r\n\x05score\x18\x03 \x01(\x01\x12\x12\n\nupdated_at\x18\x04 \x01(\x04\"A\n\nSpaceScore\x12\x10\n\x08space_id\x18\x01 \x01(\x0c\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x12\n\nupdated_at\x18\x03 \x01(\x04\"\xe1\x01\n\x11HermesScoresBatch\x12+\n\rentity_scores\x18\x01 \x03(\x0b\x32\x14.scoring.EntityScore\x12\x35\n\x12perspective_scores\x18\x02 \x03(\x0b\x32\x19.scoring.PerspectiveScore\x12)\n\x0cspace_scores\x18\x03 \x03(\x0b\x32\x13.scoring.SpaceScore\x12\x13\n\x0b\x63omputed_at\x18\x04 \x01(\x04\x12\x16\n\x0e\x62\x61tch_sequence\x18\x05 \x01(\r\x12\x10\n\x08is_final\x18\x06 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTITYSCORE']._serialized_start=26
  _globals['_ENTITYSCORE']._serialized_end=93
  _globals['_PERSPECTIVESCORE']._serialized_start=95
  _globals['_PERSPECTIVESCORE']._serialized_end=185
  _globals['_SPACESCORE']._serialized_start=187
  _globals['_SPACESCORE']._serialized_end=252
  _globals['_HERMESSCORESBATCH']._serialized_start=255
  _globals['_HERMESSCORESBATCH']._serialized_end=480
# @@protoc_insertion_point(module_scope)
