apiVersion: v1
kind: ConfigMap
metadata:
  name: protobuf-schemas
  namespace: kafka
data:
  grc20.proto: |
    syntax = "proto3";

    package grc20;

    message Op {
      oneof op {
        SetTriple set_triple = 1;
        DeleteTriple delete_triple = 2;
      }
    }

    message SetTriple {
      string entity = 1;
      string attribute = 2;
      Value value = 3;
    }

    message DeleteTriple {
      string entity = 1;
      string attribute = 2;
    }

    message Value {
      oneof value {
        string string_value = 1;
        bytes id_value = 2;
        string image_value = 3;
        string date_value = 4;
        string url_value = 5;
      }
    }

  blockchain_metadata.proto: |
    syntax = "proto3";

    package blockchain_metadata;

    message BlockchainMetadata {
        int64 created_at = 1;
        bytes created_by = 2;
        uint64 block_number = 3;
        string cursor = 4;
    }

  space.proto: |
    syntax = "proto3";

    package space;

    import "blockchain_metadata.proto";

    message PersonalSpacePayload {
        bytes owner = 1;
    }

    message DefaultDaoSpacePayload {
        repeated bytes initial_editors = 1;
        repeated bytes initial_members = 2;
    }

    message HermesCreateSpace {
        bytes space_id = 1;
        bytes topic_id = 2;

        oneof payload {
            PersonalSpacePayload personal_space = 3;
            DefaultDaoSpacePayload default_dao_space = 4;
        }

        blockchain_metadata.BlockchainMetadata meta = 5;
    }

    message VerifiedExtension {
        bytes target_space_id = 1;
    }

    message RelatedExtension {
        bytes target_space_id = 1;
    }

    message SubtopicExtension {
        bytes target_topic_id = 1;
    }

    message HermesSpaceTrustExtension {
        bytes source_space_id = 1;

        oneof extension {
            VerifiedExtension verified = 2;
            RelatedExtension related = 3;
            SubtopicExtension subtopic = 4;
        }

        blockchain_metadata.BlockchainMetadata meta = 5;
    }

  knowledge.proto: |
    syntax = "proto3";

    package knowledge;

    import "grc20.proto";
    import "blockchain_metadata.proto";

    message HermesEdit {
      bytes id = 1;
      string name = 2;
      repeated grc20.Op ops = 3;
      repeated bytes authors = 4;
      optional bytes language = 5;
      string space_id = 6;
      bool is_canonical = 7;

      blockchain_metadata.BlockchainMetadata meta = 8;
    }

  topology.proto: |
    syntax = "proto3";

    package topology;

    import "blockchain_metadata.proto";

    message CanonicalGraphUpdated {
      bytes root_id = 1;
      CanonicalTreeNode tree = 2;
      repeated bytes canonical_space_ids = 3;
      blockchain_metadata.BlockchainMetadata meta = 4;
    }

    message CanonicalTreeNode {
      bytes space_id = 1;

      oneof edge {
        RootEdge root = 2;
        VerifiedEdge verified = 3;
        RelatedEdge related = 4;
        TopicEdge topic = 5;
      }

      repeated CanonicalTreeNode children = 6;
    }

    message RootEdge {}

    message VerifiedEdge {}

    message RelatedEdge {}

    message TopicEdge {
      bytes topic_id = 1;
    }
